wandb_version: 1

num_node_features:
  desc: null
  value: 9
num_edge_features:
  desc: null
  value: 3
hidden_channels:
  desc: null
  value:
  - 64
  - 128
  - 128
  - 512
  - 512
  - 512
batch_norm:
  desc: null
  value: true
dropout:
  desc: null
  value: true
p:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.15.12
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702718905.172452
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      - 103
      3:
      - 2
      - 13
      - 16
      - 19
      - 23
      4: 3.10.2
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
Patient ID:
  desc: null
  value: jh101
Model ID:
  desc: null
  value: VICRegT1
Transfer ID:
  desc: null
  value: null
Classify:
  desc: null
  value: None
Frozen:
  desc: null
  value: null
Predictive Head:
  desc: null
  value: linear
Date & Time:
  desc: null
  value: None
Data size:
  desc: null
  value: 1.0
Total examples:
  desc: null
  value: 72912
Used examples:
  desc: null
  value: 72912
Training examples:
  desc: null
  value: 58330
Validation examples:
  desc: null
  value: 14582
Training batches:
  desc: null
  value: 228
Validation batches:
  desc: null
  value: 57
Validation ratio:
  desc: null
  value: 0.2
Test ratio:
  desc: null
  value: 0.0
Train ratio:
  desc: null
  value: null
Batch size:
  desc: null
  value: 256
Number of workers:
  desc: null
  value: 8
Learning rate:
  desc: null
  value: 0.2
Weight decay:
  desc: null
  value: 1.0e-06
Number of epochs:
  desc: null
  value: 5
Model parameters:
  desc: null
  value:
    num_node_features: 9
    num_edge_features: 3
    hidden_channels:
    - 64
    - 128
    - 128
    - 512
    - 512
    - 512
    batch_norm: true
    dropout: true
    p: 0.1
Dropout:
  desc: null
  value: true
