wandb_version: 1

num_node_features:
  desc: null
  value: 9
num_edge_features:
  desc: null
  value: 3
hidden_channels:
  desc: null
  value: 64
out_channels:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697414834.448666
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 13
      - 16
      - 19
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
Patient ID:
  desc: null
  value: jh101
Data size:
  desc: null
  value: 1.0
Total examples:
  desc: null
  value: 1113
Used examples:
  desc: null
  value: 1113
Training examples:
  desc: null
  value: 890
Validation examples:
  desc: null
  value: 223
Training batches:
  desc: null
  value: 28
Validation batches:
  desc: null
  value: 7
Validation ratio:
  desc: null
  value: 0.2
Test ratio:
  desc: null
  value: 0.1
Batch size:
  desc: null
  value: 32
Number of workers:
  desc: null
  value: 4
Learning rate:
  desc: null
  value: 0.001
Number of epochs:
  desc: null
  value: 1
Model parameters:
  desc: null
  value:
    num_node_features: 9
    num_edge_features: 3
    hidden_channels: 64
    out_channels: 32
    dropout: 0.1
