wandb_version: 1

num_node_features:
  desc: null
  value: 9
num_edge_features:
  desc: null
  value: 3
hidden_channels:
  desc: null
  value:
  - 32
  - 64
out_channels:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697414892.141152
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 13
      - 16
      - 19
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
Patient ID:
  desc: null
  value: jh101
Data size:
  desc: null
  value: 0.05
Total examples:
  desc: null
  value: 82810
Used examples:
  desc: null
  value: 4140
Training examples:
  desc: null
  value: 3312
Validation examples:
  desc: null
  value: 828
Training batches:
  desc: null
  value: 104
Validation batches:
  desc: null
  value: 26
Validation ratio:
  desc: null
  value: 0.2
Test ratio:
  desc: null
  value: 0.0
Batch size:
  desc: null
  value: 32
Number of workers:
  desc: null
  value: 4
Learning rate:
  desc: null
  value: 0.001
Number of epochs:
  desc: null
  value: 1
Model parameters:
  desc: null
  value:
    num_node_features: 9
    num_edge_features: 3
    hidden_channels:
    - 32
    - 64
    out_channels: 128
